### ISSUE TITLE
difference between  Yast2-journal and  Yast2-journalctl

### ISSUE THREAD

**Issue by Konfekt** [ancorgs/yast-journal#4]
Dear Ancor Gonzalez Sosa,

Could you explain the difference between the two packages Yast2-journal and  Yast2-journalctl you provide on the software.opensuse.org?

**Comment by ancorgs** [comment]
Yast2-journalctl should not be there :smile: It's just a result of me following this tutorial I wrote (to verify it worked) http://yast.github.io/yast-journalctl-tutorial/

Yast2-journal is a real module that I plan to greatly improve next week. Once it's ready, it will become part of the Yast:Head project (first step to officially enter Tumbleweed for a new YaST module).

**Comment by ancorgs** [comment]
I have just deleted yast2-journalctl from the build service (ergo from software.o.o) sorry for the inconveniences.

**Comment by Konfekt** [comment]
Alright, thanks for speedy response. I happend to install the right package (though it was less recent).
